version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"




  # app:
  #   build: . # Assuming the Dockerfile is in the same directory as the compose file
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/usr/src/app
