version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: english_teacher
  app:
    build: . # Assuming the Dockerfile is in the same directory as the compose file
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
